paging:
  p_5: 5
  p_8: 8
  p_10: 10
brand:
  name:
    max_length: 20
product:
  limit_img: 500
  accept_image: "image/jpeg,image/gif,image/png"
  max_name: 50
  max_price: 9
comment:
  max_content: 50
